const CFG=window.ROD_CONFIG||{API_BASE:'',DEMO_FALLBACK:true};
const API=(CFG.API_BASE||'').replace(/\/$/,'');
const $=id=>document.getElementById(id);
const state={flow:'',data:{},history:JSON.parse(localStorage.getItem('rod_history')||'[]'),results:JSON.parse(localStorage.getItem('rod_results')||'[]'),services:{},deferred:null,tts:true,listening:false};
const tools=[
 ['dni','🪪','Consultar DNI','Identidad individual por Factiliza'],['dni_match','✅','DNI + nombre','Comparación tolerante de nombre declarado'],['ruc','🏢','Consultar RUC','Ficha SUNAT, estado, condición y domicilio'],['ruc_match','🔎','RUC + razón social','Comparar declarado contra SUNAT'],['reps','👥','Representantes legales','Consulta bajo demanda'],['cpe','🧾','Validar comprobante','Factura, boleta o recibo por honorarios'],['pj','⚖️','Poder Judicial','Individual o lote, acceso asistido'],['4b','📊','Anexo 4B','Validación integral de aportantes'],['4d','📑','Anexo 4D','Proveedor + CPE + datos + PJ'],['detect','📂','Detectar archivo','ROD identifica si parece 4B o 4D'],['prevalidate','📋','ROD Check','Formato, documentos, hojas y estructura'],['multi','🗂️','Múltiples archivos','Procesamiento por lote'],['compare','↔️','Comparar','Declarado vs consultado'],['retry','🔄','Reprocesar observados','Solo fallos técnicos o pendientes'],['custom','✦','Flujo personalizado','Elige exactamente qué módulos ejecutar']
];
function rodHTML(cls='mini'){return `<div class="rod ${cls}"><div class="face"><i class="eye l"></i><i class="eye r"></i><i class="mouth"></i></div><span class="rr">R</span></div>`}
function safe(v){return String(v??'').replace(/[<>]/g,'')}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
function progress(n){$('bar').style.width=n+'%'}
function setRod(mode,text){['heroRod','floatRod'].forEach(id=>{const e=$(id);if(!e)return;e.classList.remove('listening','thinking','alert','error');if(mode)e.classList.add(mode)});if(text){$('rodPopText').textContent=text;$('rodPop').classList.add('open');setTimeout(()=>$('rodPop').classList.remove('open'),4500)}}
function speak(text){if(!state.tts||!('speechSynthesis'in window))return;const u=new SpeechSynthesisUtterance(String(text).replace(/<[^>]*>/g,''));u.lang='es-PE';u.rate=1;speechSynthesis.cancel();speechSynthesis.speak(u)}
function bot(html,voice=''){const wrap=document.createElement('div');wrap.className='msg';wrap.innerHTML=`${rodHTML('mini')}<div class="bubble"><small>ROD</small><br>${html}</div>`;$('chat').appendChild(wrap);$('chat').scrollTop=$('chat').scrollHeight;if(voice)speak(voice)}
function user(text){const w=document.createElement('div');w.className='msg user';w.innerHTML=`<div class="bubble">${safe(text)}</div>`;$('chat').appendChild(w);$('chat').scrollTop=$('chat').scrollHeight}
function actions(html){$('actions').innerHTML=html}
function openFlow(flow,title){state.flow=flow;state.data={};$('chat').innerHTML='';actions('');$('flowTitle').textContent=title||tools.find(x=>x[0]===flow)?.[2]||'Consulta';progress(8);$('flow').classList.add('open')}
function closeFlow(){setRod('', 'Listo. ¿Qué hacemos ahora?');$('flow').classList.remove('open')}
function addHistory(type,title,detail,status='OK'){state.history.unshift({time:new Date().toLocaleString('es-PE'),type,title,detail,status});state.history=state.history.slice(0,50);localStorage.setItem('rod_history',JSON.stringify(state.history));renderHistory()}
function addResult(title,detail,content){state.results.unshift({time:new Date().toLocaleString('es-PE'),title,detail,content});state.results=state.results.slice(0,30);localStorage.setItem('rod_results',JSON.stringify(state.results));renderResults()}
function renderHistory(){const el=$('historyList');if(!state.history.length){el.innerHTML='<div class="empty">Aún no hay procesos. ROD irá guardando tus consultas aquí.</div>';return}el.innerHTML=state.history.map(h=>`<div class="item"><div class="ii">${h.type||'✓'}</div><div><b>${safe(h.title)}</b><small>${safe(h.detail)}</small><small>${safe(h.time)}</small></div><span class="pill">${safe(h.status)}</span></div>`).join('')}
function renderResults(){const el=$('resultsList');if(!state.results.length){el.innerHTML='<div class="empty">Todavía no hay entregables generados.</div>';return}el.innerHTML=state.results.map((r,i)=>`<div class="item"><div class="ii">📥</div><div><b>${safe(r.title)}</b><small>${safe(r.detail)}</small><small>${safe(r.time)}</small></div><button class="ghost" data-download="${i}">Descargar</button></div>`).join('');document.querySelectorAll('[data-download]').forEach(b=>b.onclick=()=>downloadResult(+b.dataset.download))}
function downloadResult(i){const r=state.results[i];if(!r)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([r.content||r.detail],{type:'text/plain;charset=utf-8'}));a.download=(r.title||'rod_resultado').replace(/[^a-z0-9_-]+/gi,'_')+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
async function api(path,{method='POST',json=null,form=null}={}){if(!API)throw new Error('API_NOT_CONFIGURED');const opts={method,headers:{}};if(json){opts.headers['Content-Type']='application/json';opts.body=JSON.stringify(json)}if(form)opts.body=form;const r=await fetch(API+path,opts);let data={};try{data=await r.json()}catch{data={message:await r.text()}}if(!r.ok)throw new Error(data.detail||data.message||`HTTP ${r.status}`);return data}
function apiEnabled(){return !!API}
function humanError(e){const m=String(e?.message||e);if(m==='API_NOT_CONFIGURED')return 'ROD API todavía no tiene URL configurada.';return m}
function demoDelay(ms=550){return new Promise(r=>setTimeout(r,ms))}
async function checkServices(){const grid=$('serviceGrid');grid.innerHTML='<div class="serviceCard">Comprobando motores…</div>';let data=null;if(API){try{data=await api('/api/health/services',{method:'GET'});$('topStatus').textContent='ROD API conectada';$('sideApi').textContent='Conectado';$('apiText').textContent='ROD API responde correctamente.'}catch(e){$('topStatus').textContent='Backend sin respuesta';$('sideApi').textContent='Sin conexión';$('apiText').textContent='No pude conectar con ROD API: '+humanError(e)}}else{$('topStatus').textContent='Modo demo · API pendiente';$('sideApi').textContent='No configurado';$('apiText').textContent='Configura API_BASE en config.js después de desplegar ROD API.'}const svcs=data?.services||{factiliza:{configured:false,mode:'API',detail:'Falta conectar backend'},sunat_cpe:{configured:false,mode:'API',detail:'Falta conectar backend'},sunat_web:{configured:false,mode:'HEADLESS_WEB',detail:'Falta conectar backend'},pj:{configured:false,mode:'ASSISTED',detail:'PJ siempre será asistido'},batch_4b:{configured:true,mode:'DEMO',detail:'Flujo visual listo'},batch_4d:{configured:true,mode:'DEMO',detail:'Flujo visual listo'}};state.services=svcs;const labels={factiliza:['🪪','Factiliza · DNI'],sunat_cpe:['🧾','SUNAT API · CPE'],sunat_web:['🏢','SUNAT Web · RUC'],pj:['⚖️','Poder Judicial'],batch_4b:['📊','Motor 4B'],batch_4d:['📑','Motor 4D']};grid.innerHTML=Object.entries(svcs).map(([k,v])=>{const [ico,name]=labels[k]||['⚙',k];const cls=v.configured?'ok':(k==='pj'?'warn':'bad');const txt=v.configured?'CONFIGURADO':(k==='pj'?'ASISTIDO':'PENDIENTE');return `<div class="serviceCard"><div class="serviceTop"><div><span style="font-size:24px">${ico}</span><b style="display:block;margin-top:6px">${name}</b></div><span class="svcStatus ${cls}">${txt}</span></div><p>${safe(v.detail||v.mode||'')}</p></div>`}).join('');$('sidePj').textContent=svcs.pj?.configured?'Credenciales listas':'Asistido';$('apiDisplay').value=API||'(sin configurar)'}
function nav(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+name));document.querySelectorAll('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.nav===name))}
document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));
function renderTools(){const html=tools.map(t=>`<button class="tool" data-flow="${t[0]}"><span class="ico">${t[1]}</span><b>${t[2]}</b><small>${t[3]}</small></button>`).join('');$('allTools').innerHTML=html;document.querySelectorAll('[data-flow]').forEach(b=>b.onclick=()=>startFlow(b.dataset.flow))}
async function startFlow(f){if(f==='dni_match')return startDni(true);if(f==='ruc_match')return startRuc(true);if(f==='reps')return startReps();if(f==='dni')return startDni(false);if(f==='ruc')return startRuc(false);if(f==='cpe')return startCpe();if(f==='pj')return startPJ();if(f==='4b'||f==='4d')return startBatch(f.toUpperCase());if(f==='detect'||f==='prevalidate')return startDetect(f==='prevalidate');if(['multi','compare','retry','custom'].includes(f))return startUtility(f)}
